/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class abex_spng_SPNGEncoder */

#ifndef _Included_abex_spng_SPNGEncoder
#define _Included_abex_spng_SPNGEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    new0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_abex_spng_SPNGEncoder_new0
  (JNIEnv *, jclass);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    setIHDR
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_setIHDR
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    setFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_setFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    setOption
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_setOption
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    encodeImage
 * Signature: ([IIIII)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_encodeImage
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    encodeChunks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_encodeChunks
  (JNIEnv *, jobject);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    setState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_setState
  (JNIEnv *, jobject, jint);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    writeChunk0
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_writeChunk0
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    getBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_abex_spng_SPNGEncoder_getBuffer
  (JNIEnv *, jobject);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    freeBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_freeBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     abex_spng_SPNGEncoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_abex_spng_SPNGEncoder_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
